package it.unibz.inf.kaos.obdamapper.reasoner;

import it.unibz.inf.kaos.obdamapper.util.ExecutionMsgEvent;
import it.unibz.inf.kaos.obdamapper.util.ExecutionMsgListener;

public abstract class OBDAMaterializerAbstract implements OBDAMaterializer{

	//Listener for all of the execution logs generated by this class
	private ExecutionMsgListener executionLogListener;
	
	public void setExecutionLogListener(ExecutionMsgListener ell) {
		
		this.executionLogListener = ell;
	}

	protected void addNewExecutionMsg(ExecutionMsgEvent eme){
		
		if(executionLogListener != null)
			executionLogListener.addNewExecutionMsg(eme);	
	}
}
