name: Development release

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots install
      - name: Get version
        id: project
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build v${{ steps.project.outputs.version }}"
          files: |
            toolkit/target/toolkit-${{ steps.currenttag.outputs.version }}.jar
            LICENSE.txt
            README.md
